version: '{build}'
skip_non_tags: true

platform:
  - x64

environment:
  JSPM_GITHUB_AUTH_TOKEN:
    secure: cMK1oeXEY4EapDoULjfBBtJUbba/hhOZuROH+wyl08UD69h7t/V2KOFpmNeieD5J5IPV7k60HUJMMIZl/CiHJAt5upeacyn4lmnau0Lthas=

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 7 x64
  - npm install

build_script:
  - npm run build

test: off

artifacts:
  - path: dist\*.exe
    name: files

deploy:
  - provider: GitHub
    auth_token:
      secure: DLJb4fuTIyqr4yW+MYt6coUoGmnDqa7hb5Z54w7p1neAS50lgD3tRAPdGkqK8C19
    artifact: files
    on:
      appveyor_repo_tag: true
