version: '{build}'
skip_non_tags: true

platform:
  - x64

environment:
  JSPM_GITHUB_AUTH_TOKEN:
    secure: 'cMK1oeXEY4EapDoULjfBBtJUbba/hhOZuROH+wyl08UD69h7t/V2KOFpmNeieD5J5IPV7k60HUJMMIZl/CiHJAt5upeacyn4lmnau0Lthas='

cache:
  - 'app\browser\jspm_packages'
  - 'node_modules'
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build

test: off

artifacts:
  - path: dist\*.exe
    name: files

deploy:
  - provider: GitHub
    auth_token:
      secure: '1bUZKL+ODKMa687U+YZsoRX6bFgP7zcasbNxJdBIEyYHNiAli/yuF+nKkkgCCb2L'
    artifact: files
    on:
      appveyor_repo_tag: true
